{% set name = "pydlpack" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e21dfdbd31baa5745ffd4c84a829ad6177452262f1ca6cf65dbcac5f5faad07

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10

test:
  requires:
    - pip
    - pytest
    - numpy
  commands:
    - pytest -sv -r s --pyargs dlpack
    - pip check
  imports:
    - dlpack
    - dlpack.tests

about:
  home: https://github.com/pearu/pydlpack
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: DLPack data exchange interface in Python
  description: |
    PyDLPack is a Python library for exchanging data between different
    array libraries using DLPack protocol. The provider library does
    not need to implement DLPack support. Implementing CPU/CUDA array
    interface or Python buffer protocol is sufficient.
  doc_url: https://github.com/pearu/pydlpack
  dev_url: https://github.com/pearu/pydlpack

extra:
  recipe-maintainers:
    - pearu
